author: JoshuaKGoldberg
description: Runs OctoGuide as a GitHub Action. 🗺️
inputs:
  github-token:
    description: GitHub token (PAT) with repo and workflow permissions.
name: OctoGuide Action
runs:
  steps:
    - run: node dist/index.js
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  using: "composite"
