jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        name: 🪙 Get app token
        uses: actions/create-github-app-token@7bd03711494f032dfa3be3558f7dc8787b0be333 # v3.1.0
        with:
          app-id: ${{ vars.all_contributors_app_id }}
          private-key: ${{ secrets.all_contributors_private_key }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        uses: JoshuaKGoldberg/all-contributors-auto-action@587a3a5844b0104abb911a69a1a84ec645292f5e # v0.6.0

name: Contributors

on:
  push:
    branches:
      - main
