jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        name: 🪙 Get app token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ vars.all_contributors_app_id }}
          private-key: ${{ secrets.all_contributors_private_key }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        uses: JoshuaKGoldberg/all-contributors-auto-action@587a3a5844b0104abb911a69a1a84ec645292f5e # v0.6.0

name: Contributors

on:
  push:
    branches:
      - main
