jobs:
  octoguide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: node dist/index.js

name: OctoGuide

on:
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, deleted, edited]
  issue_comment:
    types: [created, deleted, edited]
  issues:
    types: [edited, opened]
  pull_request_review_comment:
    types: [created, deleted, edited]
  pull_request_target:
    types: [edited, opened]
permissions:
  discussions: write
  issues: write
  pull-requests: write
